### ISSUE TITLE
Import prices URL in Admin is broken

### ISSUE THREAD

**Issue by bellu** [Brille24/SyliusCustomOptionsPlugin#135]
I'm using Sylius 1.10.9 with php 7.4.20.

I tried to upload the prices from this URL -> /admin/customer-options/import-prices but i got this error:

"brille24.sylius_customer_options_plugin.controller.price_import_controller" has no container set, did you forget to define it as a service subscriber?

I saw that there's a similar issue [https://github.com/Brille24/SyliusCustomOptionsPlugin/issues/111](#111 ) but it refers to another URL.

How can i solve this?

**Comment by mamazu** [comment]
Hey, thanks for bringing this up. It looks like you are using an older version of php and Sylius. Would you mind checking for me which Symfony version you are running?

We definitely need to update this class anyways to not require a container but that is probably not going to help you right now.

**Comment by bellu** [comment]
The Symfony version is the 5.4.22.
We've already scheduled an update for this e-commerce, in the meantime can you give any clue to fix this? 
Thanks

**Comment by mamazu** [comment]
Hm strange, it should work with 5.4.22.

What you could do as a quick and dirty fix is to add a method call to this service and set the container. You will probably have to copy the configuration from the bundle for this service and add a call to `setContainer` like described here: 
https://symfony.com/doc/5.4/service_container/calls.html

**Comment by bellu** [comment]
@mamazu Thanks for your suggestions, but the service container call seems not working

``` 
    Brille24\SyliusCustomerOptionsPlugin\Importer\CustomerOptionPriceImporterInterface: '@brille24.sylius_customer_options_plugin.importer.customer_option_price_importer'
    Brille24\SyliusCustomerOptionsPlugin\Handler\ImportErrorHandlerInterface: '@brille24.sylius_customer_options_plugin.handler.csv_import_error_handler'
    
    brille24_customer_option_price_import:
        class: Brille24\SyliusCustomerOptionsPlugin\Controller\PriceImportController
        arguments:
            $csvExampleFilePath: '%brille24.sylius_customer_options.price_import_example_file_path%'
        calls:
            - [ setContainer, [ "@service_container" ] ]
```

So i created a new controller, just a copy paste in my project with this configuration: 
```  
    Brille24\SyliusCustomerOptionsPlugin\Importer\CustomerOptionPriceImporterInterface: '@brille24.sylius_customer_options_plugin.importer.customer_option_price_importer'
    Brille24\SyliusCustomerOptionsPlugin\Handler\ImportErrorHandlerInterface: '@brille24.sylius_customer_options_plugin.handler.csv_import_error_handler'

       App\Controller\Admin\CustomPriceImportController:
        arguments:
            $csvExampleFilePath: '%brille24.sylius_customer_options.price_import_example_file_path%'
        autowire: true 
``` 

PS: you need to add the annotations to the controller, something like this:

```  
/**
 * @Route("/admin/customer-options/import-prices", name="admin_custom_import_prices")
 */
class CustomPriceImportController extends AbstractController
...
``` 

I know that i a dirty trick, but it's working.
