### ISSUE TITLE
Overriding CustomerOptionValue

### ISSUE THREAD

**Issue by dominx99** [Brille24/SyliusCustomOptionsPlugin#72]
Is there a possibility to override Entity?
I want to add one more column to the "brille24_customer_option_value" table

I created a new entity that extends CustomerOptionValue
```
/**
 * @ORM\Entity
 * @ORM\Table(name="brille24_customer_option_value")
 */
class CustomerOptionValue extends BaseCustomerOptionValue
{
    /**
     * @ORM\Column(type="integer", name="external_id", nullable=true)
     */
    protected $externalId;
}
```

Changed model class to the new one _config/packages/resources.yml_
```
sylius_resource:
    resources:
        brille24.customer_option_value:
            classes:
                model: \App\Entity\CustomerOption\CustomerOptionValue
                repository: Brille24\SyliusCustomerOptionsPlugin\Repository\CustomerOptionValueRepository
                factory: Brille24\SyliusCustomerOptionsPlugin\Factory\CustomerOptionValueFactory
                form: Brille24\SyliusCustomerOptionsPlugin\Form\CustomerOptionValueType
            translation:
                classes:
                    model: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValueTranslation
                    form: Brille24\SyliusCustomerOptionsPlugin\Form\CustomerOptionValueTranslationType
```

but when run ```php bin/console doctrine:migrations:diff``` I am getting:

The table with name 'sylius.brille24_customer_option_value' already exists.

**Comment by mamazu** [comment]
Thanks for spotting the error. The entities were not marked in the plugin as `mapped-superclass` so they weren't extendable. This was just fixed and will be available in the next version. Then you should be able to extend the entity.

If you still have issues with extending the entity it might be because of the change in configuration language. Our plugin uses XML to define the entity mappings. This might clash with your annotation mappings.

**Comment by dominx99** [comment]
Thank you for your detailed reply.
I have one more question. Is it possible to override your CustomerOptionValue.orm.xml in older versions of this plugin?
I am asking because I would want to mark this from entity to mapped-superclass.

**Comment by mamazu** [comment]
I have replaced (almost all) entity definitions with `mapped-superclass`es in the `.orm.xml` files. I am currently waiting for the pipeline to be green to tag it as a new version then they should be extendable.

What version do you want to modify? Do you need an older version of the plugin to be extendable or what is your goal?

**Comment by dominx99** [comment]
I am actually using the 2.7 version, so if there are no breaking changes I can upgrade to this newest one.
Cool that you did that when I needed it.

**Comment by mamazu** [comment]
If you are already on 1.8 then you should update to the newest version as this includes importer fixes and performance improvements for the backend. New version is tagged so just updating the package should do the trick.

Feel free to let me know if it works or if there are still any other issues.

**Comment by dominx99** [comment]
Unfortunatelly translation does not work for me now.
I was trying to add
```

    protected function createTranslation(): TranslationInterface
    {
        return new CustomerOptionValueTranslation();
    }
```
to my new Entity class
config/packages/resources.yml
```
sylius_resource:
    resources:
        brille24.customer_option_value:
            classes:
                model: \App\Entity\CustomerOption\CustomerOptionValue
            translation:
                classes:
                    model: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValueTranslation
```
